
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: default
 spec:
   serviceAccountName: default
   automountServiceAccountToken: false


secret:
- name: default-secret
  annotations:
    kubernetes.io/service-account.name: default
type: kubernetes.io/service-account-token


